In [ ]:
# numpy is a library that allows for the use of arrays  
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [5]:
type(a)

numpy.ndarray

Basic operation of Array.

In [7]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [8]:
# Creating a 2D array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
# Creating a 3D array.
a=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [14]:
# Method
print(a.shape) #(2,2,2) 2 arrays, 2 row,2 column


(1, 4, 2)


In [ ]:
print(a.ndim) # array type find out .

3


In [17]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y=np.array([[[6,7,5],[10,11,12],[13,14,15]]])
print(x)
print(y)
print(x.ndim)
print(y.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 6  7  5]
  [10 11 12]
  [13 14 15]]]
3
3


In [ ]:
print(a.dtype) # find out the array in element.

int64


In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [22]:
np.random.randint(10,30, size=(3,3))

array([[12, 17, 26],
       [22, 25, 29],
       [11, 15, 18]], dtype=int32)

In [23]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y=np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [6]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) # it gives the variance of all the elements of the array.
print(x.std()) # it gives the standard deviation of all the elements of the array.


106
726.1224489795919
26.94665932874782


In [7]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) # it gives the 25th percentile of the array
print(np.percentile(a,50)) # it gives the 50th percentile of the arra
print(np.percentile(a,75)) # it gives the 75th percentile of the arra

3.0
5.0
7.0


In [9]:
arr=np.random.randint(10,50,size=(4,4))
print(arr)

[[41 25 45 43]
 [18 33 49 39]
 [29 28 33 36]
 [35 17 47 29]]


In [11]:
print(arr.reshape(8,2))
print()
print(arr.reshape(2,8))

[[41 25]
 [45 43]
 [18 33]
 [49 39]
 [29 28]
 [33 36]
 [35 17]
 [47 29]]

[[41 25 45 43 18 33 49 39]
 [29 28 33 36 35 17 47 29]]


In [ ]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
print(x)
print(x[0,0])


[[7 2 3]
 [2 5 2]
 [3 5 1]]
7


In [16]:
print(x[:3])
print(x[3:])
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[]
[[3 5 1]]


Spacial Numpy Array

In [2]:
# Zeros Function
import numpy as np
ay_ze=np.zeros(4)
print(ay_ze)

[0. 0. 0. 0.]


In [4]:
import numpy as np
ay_zero1=np.zeros((3,4))
print(ay_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
import numpy as np
b=np.zeros((2,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#ones function
import numpy as np
ay_one=np.ones((4,6))
print(ay_one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
ar_one1=np.ones(4)
print(ar_one1)

[1. 1. 1. 1.]


In [ ]:
# Empty array
import numpy as np 
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [11]:
# Range function
ar_ran=np.arange(0,10,2)
print(ar_ran)

[0 2 4 6 8]


In [14]:
#Diagonal Array
import numpy as np
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
import numpy as np
ar_dia1=np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
# linspace function
import numpy as np
lin_spe=np.linspace(0,20, num=5)
print(lin_spe)

[ 0.  5. 10. 15. 20.]


Random function in Array
-rand()
-randn()
-ranf()
-randint()

In [18]:
# rand()
import numpy as np
var1=np.random.rand(4)
print(var1)

[0.23480678 0.76684603 0.2937078  0.48753998]


In [20]:
# randn()
import numpy as np
var2=np.random.randn(3)
print(var2)

[-0.98751192 -1.80274462  0.3807829 ]


In [21]:
# ranf()
import numpy as np
var3=np.random.ranf(3)
print(var3)

[0.46796918 0.70054249 0.78084155]


In [22]:
# randint
import numpy as np
var4=np.random.randint(1,10,5)
print(var4)

[9 9 5 9 1]


Data Types in numpy Array.

In [1]:
import numpy as np
var7=np.array([1,2,3,4,5])
print(var7.dtype)

int64


In [2]:
import numpy as np
var8=np.array([1.2,6.7,99.0,22.1])
print(var8.dtype)

float64


In [3]:
import numpy as np
var11=np.array(["s","y","u","k"])
print(var11.dtype)

<U1


DataTypes convert to another datatype.


In [1]:
# datatypes
import numpy as np
x=np.array([1,2,3,4],dtype="f")
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [2]:
import numpy as np
y=np.array([2,3,4,5,6])
c=y.astype(float)
print(y)
print(c)

[2 3 4 5 6]
[2. 3. 4. 5. 6.]


In [ ]:
# Reshape - one dimensional convert into multidimensional array.
import numpy as np
var2=np.array([1,2,3,4,5,6])
print(var2.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np # Two dimensional array to convert one dimensional array
h=np.array([[1,2,3,4],[5,6,7,8]])
print(h.reshape(-1))

[1 2 3 4 5 6 7 8]


Arithmetic operation.

In [6]:
# One D Array
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a+b)

[3 5 7 9]


In [7]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a-b)

[-1 -1 -1 -1]


In [8]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


In [11]:
# Two D Array
import numpy as np
u=np.array([[6,7,8,9],[1,3,4,5]])
v=np.array([[2,3,6,5],[2,4,3,6]])
print(u+v)


[[ 8 10 14 14]
 [ 3  7  7 11]]


In [12]:
import numpy as np
u=np.array([[6,7,8,9],[1,3,4,5]])
v=np.array([[2,3,6,5],[2,4,3,6]])
print(u-v)


[[ 4  4  2  4]
 [-1 -1  1 -1]]


In [13]:
# Arithmethic Function-min(),max(),argmin(),sqrt(),sin(),cos(),cumsum().
import numpy as np
var2=np.array([1,2,3,4,5,4,4])
print(np.min(var2))



1


In [ ]:
import numpy as np
var2=np.array([1,2,3,4,5,4,4])
print(np.min(var2))



5


In [19]:
import numpy as np
var2=np.array([1,2,3,4,5,4,4])
print(np.argmin(var2))
print(np.argmax(var2))
print(np.sqrt(var2))



0
4
[1.         1.41421356 1.73205081 2.         2.23606798 2.
 2.        ]


In [21]:
# Two D Array
import numpy as np
y=np.array([[1,2,10,5],[4,5,7,8]])
print(np.min(y,axis=0))


[1 2 7 5]


In [23]:
import numpy as np
a=np.array([1,2,3])
print(np.sin(a))
print(np.cos(a))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


Indexing in numpy

In [25]:
# 1D array
import numpy as np
var5=np.array([1,2,4,5,6])
print(var5[3])
print(var5[2])
print(var5[-2])

5
4
5


In [27]:
# 2D array
import numpy as np
var=np.array([[6,7,5,10],[3,7,11,12]])
print(var[0,2])
print(var[1,3])
print(var[1,-3])

5
12
7


In [28]:
# 3D array
import numpy as array
var3=np.array([[[1,3,6,8],[11,22,33,44]]])
print(var3[0,1,1])

22


Slicing in to numpy array.

In [4]:
# 1D array
import numpy as np
y=np.array([1,2,4,5,6,7,8])
print(y[0:5])
print(y[::2])
print(y[2:])
print(y[:6])

[1 2 4 5 6]
[1 4 6 8]
[4 5 6 7 8]
[1 2 4 5 6 7]


In [7]:
# 2D array
import numpy as np
x=np.array([[1,2,3,4,5],[7,8,4,3,2]])
print(x[0,:5])
print(x[1,1:])
print(x[1,::-1])

[1 2 3 4 5]
[8 4 3 2]
[2 3 4 8 7]


Iterating into numpy Array.


In [8]:
# 1D array
import numpy as np
var=np.array([1,2,3,4,5,6])
for i in var:
    print(i)

1
2
3
4
5
6


In [9]:
# 2D array
import numpy as np
var1=np.array([[2,3,4,5],[7,6,5,4]])
for i in var1:
    for j in i:
        print(j)

2
3
4
5
7
6
5
4


In [11]:
# 3D array
import numpy as np
var2=np.array([[[1,2,3,4],[5,6,7,8]]])
print(var2.ndim)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k)

3

1
2
3
4
5
6
7
8


In [12]:
# nditer() using iterating
import numpy as np
var3=np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
for i in np.nditer(var3):
    print(i)


1
2
3
4
5
6
7
8
9
0


In [ ]:
import numpy as np # index value find out the data
var4=np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
for i,d in np.ndenumerate(var4):
    print(i,d)


(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 0


Join and Split Function.


In [ ]:
# join()- joins means putting contents of two or more arrays in a single array.
# 1D array
import numpy as np
var9=np.array([1,2,3,4])
var10=np.array([5,6,7,8])
ar_new=np.concatenate((var9,var10))
print(ar_new)

[1 2 3 4 5 6 7 8]


In [17]:
# 2D array
import numpy as np
var11=np.array([[1,2,3,4],[5,6,7,8]])
var13=np.array([[1,2,3,4],[4,5,6,3]])
new_ar=np.concatenate((var11,var13),axis=1)
print(new_ar)
print()
new_arr=np.concatenate((var11,var13),axis=0)
print(new_arr)


[[1 2 3 4 1 2 3 4]
 [5 6 7 8 4 5 6 3]]

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [4 5 6 3]]


In [21]:
# Split()- splitting breaks one array into multiple.
import numpy as np
v=np.array([1,2,3,4])
x=np.array_split(v,2)
print(x)
print(x[0])
print(x[1])

[array([1, 2]), array([3, 4])]
[1 2]
[3 4]


Numpy Array some Function.
(Search,Sort,search sorted,Filter)

In [22]:
# Search
import numpy as np
varu=np.array([1,4,7,8,9,10,11,12,13,14,13,13,16])
x=np.where(varu==13)
print(x)

(array([ 8, 10, 11]),)


In [23]:
#sort
import numpy as np
var_6=np.array([8,7,9,2,5,10,20,11])
print(np.sort(var_6))

[ 2  5  7  8  9 10 11 20]


In [24]:
# srarch sorted
import numpy as np
b=np.array([1,2,3,4,7,8,9])
x=np.searchsorted(b,5)
print(x)

4


In [ ]:
# some importent Function
# Flatten- 2D Array convert into 1D Array.
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y.flatten())
print(y.flatten(order="F"))
print(y.flatten(order="c"))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]


In [8]:
# Resize -array shape is change
import numpy as np
g=np.array([1,2,3,4,5,6])
f=np.resize(g,(2,3))
print(f)

[[1 2 3]
 [4 5 6]]


In [9]:
# unique()
uni_f=np.array([1,2,3,4,3,2,4,5,6,3])
y=np.unique(uni_f)
print(y) 

[1 2 3 4 5 6]


In [ ]:
# shuffle()-change into position
arr_s=np.array([1,2,3,4,5])
np.random.shuffle(arr_s)
print(arr_s)

[5 3 2 1 4]


In [ ]:
# insert()
# 1D array
var1=np.array([1,2,4,3,5])
v=np.insert(var1,2,40)
print(v)


[ 1  2 40  4  3  5]


In [19]:
var2=np.array([1,2,4,3,5])
v1=np.insert(var2,(2,4),40)
print(v1)


[ 1  2 40  4  3 40  5]


In [20]:
#2D array
var3=np.array([[1,2,3],[1,2,3]])
v22=np.insert(var3,2,[22,33,44],axis=0)
print(v22)

[[ 1  2  3]
 [ 1  2  3]
 [22 33 44]]


In [21]:
# Append()
var4=np.array([22,33,5,66,77])
v5=np.append(var4,12)
print(v5)

[22 33  5 66 77 12]


In [22]:
# Delete()
var1=np.array([1,2,5,4,6,7,8,9])
c=np.delete(var1,5) 
print(c)

[1 2 5 4 6 8 9]


In [1]:
import numpy as np
a=np.array([2,3,4,5,6])
b=np.array([2,3,4,5,6])
print(a.dot(b))

90


In [3]:
# prod() -it gives multiplication of all the elements of the array
a=np.array([[1,2,3,4],[3,4,2,1]])
print(a.prod())
print(a)


576
[[1 2 3 4]
 [3 4 2 1]]


In [4]:
x=np.array([2,3,2,5,6,7,81])
print(x.min())

2


In [5]:
x.mean(axis=0) # it gives the mean of each columns

np.float64(15.142857142857142)