In [ ]:
# numpy is a library that allows for the use of arrays  
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [5]:
type(a)

numpy.ndarray

Basic operation of Array.

In [7]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [8]:
# Creating a 2D array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
# Creating a 3D array.
a=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [14]:
# Method
print(a.shape) #(2,2,2) 2 arrays, 2 row,2 column


(1, 4, 2)


In [ ]:
print(a.ndim) # array type find out .

3


In [17]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y=np.array([[[6,7,5],[10,11,12],[13,14,15]]])
print(x)
print(y)
print(x.ndim)
print(y.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 6  7  5]
  [10 11 12]
  [13 14 15]]]
3
3


In [ ]:
print(a.dtype) # find out the array in element.

int64


In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [22]:
np.random.randint(10,30, size=(3,3))

array([[12, 17, 26],
       [22, 25, 29],
       [11, 15, 18]], dtype=int32)

In [23]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y=np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]
