In [ ]:
# numpy is a library that allows for the use of arrays  
import numpy as np

In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [5]:
type(a)

numpy.ndarray

Basic operation of Array.

In [7]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [8]:
# Creating a 2D array
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [10]:
# Creating a 3D array.
a=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [14]:
# Method
print(a.shape) #(2,2,2) 2 arrays, 2 row,2 column


(1, 4, 2)


In [ ]:
print(a.ndim) # array type find out .

3


In [17]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y=np.array([[[6,7,5],[10,11,12],[13,14,15]]])
print(x)
print(y)
print(x.ndim)
print(y.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 6  7  5]
  [10 11 12]
  [13 14 15]]]
3
3


In [ ]:
print(a.dtype) # find out the array in element.

int64


In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [22]:
np.random.randint(10,30, size=(3,3))

array([[12, 17, 26],
       [22, 25, 29],
       [11, 15, 18]], dtype=int32)

In [23]:
x=np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y=np.array([[1,8,3],
            [3,7,2],
            [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


Spacial Numpy Array

In [2]:
# Zeros Function
import numpy as np
ay_ze=np.zeros(4)
print(ay_ze)

[0. 0. 0. 0.]


In [4]:
import numpy as np
ay_zero1=np.zeros((3,4))
print(ay_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
import numpy as np
b=np.zeros((2,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
#ones function
import numpy as np
ay_one=np.ones((4,6))
print(ay_one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [9]:
import numpy as np
ar_one1=np.ones(4)
print(ar_one1)

[1. 1. 1. 1.]


In [ ]:
# Empty array
import numpy as np 
ar_em=np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [11]:
# Range function
ar_ran=np.arange(0,10,2)
print(ar_ran)

[0 2 4 6 8]


In [14]:
#Diagonal Array
import numpy as np
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
import numpy as np
ar_dia1=np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [17]:
# linspace function
import numpy as np
lin_spe=np.linspace(0,20, num=5)
print(lin_spe)

[ 0.  5. 10. 15. 20.]


Random function in Array
-rand()
-randn()
-ranf()
-randint()

In [18]:
# rand()
import numpy as np
var1=np.random.rand(4)
print(var1)

[0.23480678 0.76684603 0.2937078  0.48753998]


In [20]:
# randn()
import numpy as np
var2=np.random.randn(3)
print(var2)

[-0.98751192 -1.80274462  0.3807829 ]


In [21]:
# ranf()
import numpy as np
var3=np.random.ranf(3)
print(var3)

[0.46796918 0.70054249 0.78084155]


In [22]:
# randint
import numpy as np
var4=np.random.randint(1,10,5)
print(var4)

[9 9 5 9 1]


Data Types in numpy Array.

In [1]:
import numpy as np
var7=np.array([1,2,3,4,5])
print(var7.dtype)

int64


In [2]:
import numpy as np
var8=np.array([1.2,6.7,99.0,22.1])
print(var8.dtype)

float64


In [3]:
import numpy as np
var11=np.array(["s","y","u","k"])
print(var11.dtype)

<U1


DataTypes convert to another datatype.


In [1]:
# datatypes
import numpy as np
x=np.array([1,2,3,4],dtype="f")
print(x)
print(x.dtype)

[1. 2. 3. 4.]
float32


In [2]:
import numpy as np
y=np.array([2,3,4,5,6])
c=y.astype(float)
print(y)
print(c)

[2 3 4 5 6]
[2. 3. 4. 5. 6.]
